<?php

return [
    'brand' => [
        'name' => env('APP_NAME', 'FreedomCircle Admin'),
        'tagline' => 'FreedomCircle SaaS Operations',
    ],

    'roles' => [
        'super_admin' => [
            'label' => 'Super Admin',
            'permissions' => ['*'],
        ],
        'admin' => [
            'label' => 'Admin',
            'permissions' => [
                'dashboard.view',
                'users.manage',
                'profiles.manage',
                'organizations.manage',
                'groups.manage',
                'community.manage',
                'prayer.manage',
                'recovery.manage',
                'quiet_time.manage',
                'support.manage',
                'notifications.manage',
                'app_content.manage',
                'settings.manage',
                'reports.manage',
                'audit_logs.view',
                'search.view',
                'storage.manage',
                'chat.moderate',
            ],
        ],
        'moderator' => [
            'label' => 'Moderator',
            'permissions' => [
                'dashboard.view',
                'reports.manage',
                'chat.moderate',
                'community.manage',
                'prayer.manage',
                'support.manage',
            ],
        ],
        'finance' => [
            'label' => 'Finance',
            'permissions' => [
                'dashboard.view',
                'subscriptions.manage',
                'payments.manage',
                'payouts.manage',
                'revenuecat.manage',
                'monetization.analytics',
                'bookings.manage',
            ],
        ],
        'content_manager' => [
            'label' => 'Content Manager',
            'permissions' => [
                'dashboard.view',
                'quiet_time.manage',
                'programs.manage',
                'app_content.manage',
                'notifications.manage',
                'recovery.manage',
            ],
        ],
        'church_support' => [
            'label' => 'Church Support',
            'permissions' => [
                'dashboard.view',
                'organizations.manage',
                'groups.manage',
                'support.manage',
                'subscriptions.manage',
            ],
        ],
        'helper_verification' => [
            'label' => 'Helper Verification',
            'permissions' => [
                'dashboard.view',
                'helpers.manage',
                'reports.manage',
            ],
        ],
    ],

    'modules' => [
        'dashboard' => ['label' => 'Dashboard', 'icon' => 'chart-line', 'permission' => 'dashboard.view'],
        'users' => ['label' => 'Users', 'icon' => 'users', 'permission' => 'users.manage', 'table' => 'profiles'],
        'profiles' => ['label' => 'Profiles & Roles', 'icon' => 'id-badge', 'permission' => 'profiles.manage', 'table' => 'profiles'],
        'organizations' => ['label' => 'Organizations', 'icon' => 'church', 'permission' => 'organizations.manage', 'table' => 'organizations'],
        'groups' => ['label' => 'Groups', 'icon' => 'layer-group', 'permission' => 'groups.manage', 'table' => 'groups'],
        'chat' => ['label' => 'Chat Moderation', 'icon' => 'comments', 'permission' => 'chat.moderate', 'table' => 'chat_messages'],
        'community' => ['label' => 'Community', 'icon' => 'people-group', 'permission' => 'community.manage', 'table' => 'community_posts'],
        'prayer-requests' => ['label' => 'Prayer Requests', 'icon' => 'hands-praying', 'permission' => 'prayer.manage', 'table' => 'prayer_requests'],
        'recovery' => ['label' => 'Recovery', 'icon' => 'heartbeat', 'permission' => 'recovery.manage', 'table' => 'recovery_categories'],
        'quiet-time' => ['label' => 'Quiet Time', 'icon' => 'book-open', 'permission' => 'quiet_time.manage', 'table' => 'quiet_time_sessions'],
        'quiet-time-videos' => ['label' => 'Quiet Time Videos', 'icon' => 'video', 'permission' => 'quiet_time.manage', 'table' => 'quiet_time_sessions'],
        'journal' => ['label' => 'Journal Analytics', 'icon' => 'book', 'permission' => 'users.manage', 'table' => 'journal_entries'],
        'helpers' => ['label' => 'Helpers & Coaches', 'icon' => 'user-check', 'permission' => 'helpers.manage', 'table' => 'helpers'],
        'bookings' => ['label' => 'Bookings', 'icon' => 'calendar-check', 'permission' => 'bookings.manage', 'table' => 'bookings'],
        'support-requests' => ['label' => 'Support Requests', 'icon' => 'life-ring', 'permission' => 'support.manage', 'table' => 'support_requests'],
        'subscriptions' => ['label' => 'Subscriptions', 'icon' => 'credit-card', 'permission' => 'subscriptions.manage', 'table' => 'subscriptions'],
        'revenuecat' => ['label' => 'RevenueCat', 'icon' => 'wallet', 'permission' => 'revenuecat.manage', 'table' => 'revenuecat_customers'],
        'paywall-analytics' => ['label' => 'Paywall Analytics', 'icon' => 'chart-pie', 'permission' => 'monetization.analytics', 'table' => 'paywall_events'],
        'feature-usage' => ['label' => 'Feature Usage', 'icon' => 'chart-bar', 'permission' => 'monetization.analytics', 'table' => 'feature_usage'],
        'payments' => ['label' => 'Payments', 'icon' => 'money-bill', 'permission' => 'payments.manage', 'table' => 'payments'],
        'payouts' => ['label' => 'Payouts', 'icon' => 'hand-holding-dollar', 'permission' => 'payouts.manage', 'table' => 'coach_payouts'],
        'programs' => ['label' => 'Programs', 'icon' => 'graduation-cap', 'permission' => 'programs.manage', 'table' => 'paid_programs'],
        'notifications' => ['label' => 'Notifications', 'icon' => 'bell', 'permission' => 'notifications.manage', 'table' => 'notification_templates'],
        'app-content' => ['label' => 'App Content', 'icon' => 'file-lines', 'permission' => 'app_content.manage', 'table' => 'app_content_blocks'],
        'app-settings' => ['label' => 'App Settings', 'icon' => 'gear', 'permission' => 'settings.manage', 'table' => 'app_settings'],
        'reports' => ['label' => 'Reports & Safety', 'icon' => 'shield-halved', 'permission' => 'reports.manage', 'table' => 'reports'],
        'search' => ['label' => 'Search', 'icon' => 'search', 'permission' => 'search.view', 'table' => null],
        'audit-logs' => ['label' => 'Audit Logs', 'icon' => 'clipboard-list', 'permission' => 'audit_logs.view', 'table' => 'audit_logs'],
        'storage' => ['label' => 'Storage', 'icon' => 'database', 'permission' => 'storage.manage', 'table' => 'storage_assets'],
    ],

    'settings_groups' => [
        'general',
        'feature_toggles',
        'free_plan_limits',
        'chat',
        'monetization',
        'safety',
        'notifications',
        'storage',
        'quiet_time',
        'recovery',
    ],
];
